HermesGermany/galapagos

- .github/workflows/maven.yml
- pom.xml
Some commits have gone directly to main branch instead of next_minor. This PR pulls them into our actual development branch.
> Merge main branch into next_minor

- ui/src/app/layout/topics/single-topic.component.html
- ui/src/app/layout/topics/single-topic.component.ts
- ui/src/app/shared/services/topics.service.ts
- ui/tslint.json
This Pull Request implements the feature of showing on the single topic page, which offset belongs to which partition. You can see this information by clicking on the "show topic button".
> Show partition index for a offset on the topic page

- src/main/java/com/hermesworld/ais/galapagos/topics/controller/TopicController.java
- src/main/java/com/hermesworld/ais/galapagos/topics/controller/UpdateTopicDto.java
- src/test/java/com/hermesworld/ais/galapagos/topics/controller/TopicControllerTest.java
- src/test/java/com/hermesworld/ais/galapagos/topics/service/impl/TopicServiceImplTest.java
- ui/src/app/layout/topics/single-topic.component.html
- ui/src/app/layout/topics/single-topic.component.ts
- ui/src/app/shared/services/topics.service.ts
- ui/src/assets/i18n/de.json
This Pull Request implements the feature of changing the Description of a given Topic after its creation. You can only change the  Description if you own the Topic and you are not on the staged Environment, that is if you have staged a Topic from Dev to Prod you can only change the Description on Dev, on the prod Environment the Button for editing the Description will not appear!
> Edit description of topics

- ui/src/app/layout/applications/application-block.component.html
- ui/src/app/layout/applications/application-block.component.spec.ts
This Pull Request adds the missing UI Test for the naminig pattern added with the Pull Request #24. The Test ensures that correct prefixes are shown for a given Application.
> Add UI-Test that ensures that correct prefixes are shown in "My Applications" table

- ui/src/app/layout/topics/schema-section.component.html
> Bugfix: Visibility of Delete Schema Button

- ui/src/assets/i18n/de.json
> Add missing translations

- pom.xml
This PR just triggers the draft of the Galapagos 2.1.0 release. See release notes for details.
> Galapagos Release 2.1.0

- src/main/java/com/hermesworld/ais/galapagos/kafka/impl/KafkaRepositoryContainerImpl.java
> Use only one partition for metadata topics

- ui/src/assets/i18n/en.json
> Fix Translation in "delete topic" dialogue

- src/main/java/com/hermesworld/ais/galapagos/schemas/SchemaUtil.java
- src/test/java/com/hermesworld/ais/galapagos/schema/SchemaUtilTest.java
- src/test/resources/schema-compatibility/test09a.schema.json
- src/test/resources/schema-compatibility/test09b.schema.json
- src/test/resources/schema-compatibility/test09c.schema.json
> Fix #161: Compat check fails for removed optional props

- src/main/java/com/hermesworld/ais/galapagos/ccloud/auth/ConfluentCloudAuthenticationModule.java
This fixes the error to create a new service account if the username is a email.
> Change name of developer Account

- pom.xml
- ui/src/app/layout/user-settings/user-settings.component.ts
- ui/src/assets/i18n/de.json
- ui/src/assets/i18n/en.json
This is a hotfix for a wrong text template in the UI in 2.4.0, which we wanted to provide a quick bugfix for.
> Hotfix 2.4.1

- pom.xml
- src/main/java/com/hermesworld/ais/galapagos/adminjobs/impl/SingleClusterAdminJob.java
- src/main/java/com/hermesworld/ais/galapagos/adminjobs/impl/UpdateConfluentAuthMetadataJob.java
- src/main/java/com/hermesworld/ais/galapagos/ccloud/apiclient/ServiceAccountInfo.java
- src/main/java/com/hermesworld/ais/galapagos/ccloud/auth/ConfluentCloudAuthenticationModule.java
- src/main/java/com/hermesworld/ais/galapagos/kafka/auth/KafkaAuthenticationModule.java
- ui/src/app/layout/applications/application-block.component.html
- ui/src/app/layout/applications/application-block.component.spec.ts
- ui/src/app/layout/applications/application-block.component.ts
- ui/src/app/layout/staging/staging.component.html
- ui/src/app/layout/staging/staging.component.ts
- ui/src/app/shared/services/apikey.service.ts
> Calculated staging is not resetted when changing the application #187

- ui/src/app/layout/components/sidebar/sidebar.component.scss
> Fix scrollbar in darkmode

- ui/src/app/layout/topics/subscribesection/subscribe-section.component.html
- ui/src/assets/i18n/de.json
- ui/src/assets/i18n/en.json
> Note on staging for topic subscriptions

- demo-ccloud/setup-demo.sh
* Better error log for import errors
* wait for API key to be provisioned
* Create PROD cluster first, so API key has better chance to be provisioned
> [ccloud setup script] More resilient data import

- src/main/java/com/hermesworld/ais/galapagos/notifications/impl/NotificationEventListener.java
- src/main/resources/mailtemplates/new-producer-added.html
- src/main/resources/mailtemplates/producer-deleted.html
- start-keycloak.sh
This fixes some issues which have been overlooked when reviewing #216 and have only been detected during testing.
> Fix some producer e-mail related issues

- pom.xml
- ui/src/styles/_accordion-fixes.scss
- ui/src/styles/app.scss
This fixes a CSS bug of the accordion panel used on "My Applications" and "Create Topic" pages in Darkmode.
> Hotfix Release 2.6.2

- src/main/java/com/hermesworld/ais/galapagos/ccloud/auth/ConfluentCloudAuthConfig.java
- src/main/java/com/hermesworld/ais/galapagos/devauth/impl/DevUserAclListener.java
- src/main/java/com/hermesworld/ais/galapagos/kafka/config/KafkaEnvironmentConfig.java
- src/main/java/com/hermesworld/ais/galapagos/kafka/config/impl/KafkaEnvironmentConfigImpl.java
- src/test/java/com/hermesworld/ais/galapagos/devauth/impl/DevUserAclListenerTest.java
- src/test/java/com/hermesworld/ais/galapagos/kafka/util/AclSupportTest.java
> Add per-env writeAccess flag for developer authentications

- pom.xml
- src/test/java/com/hermesworld/ais/galapagos/ccloud/ConfluentCloudApiClientTest.java
- src/test/java/com/hermesworld/ais/galapagos/schema/SchemaCompatibilityValidatorTest.java
- src/test/java/com/hermesworld/ais/galapagos/security/impl/OAuthConfigControllerIntegrationTest.java
Also, this replaces MockWebServer with WireMock, which provides a nicer and shorter testing API.
> Update to Spring Boot 3.2.3

- pom.xml
* Update Spring Boot to 3.2.6
* Update BouncyCastle to 1.78
> Update Dependencies for security fixes

- eclipse-code-formatter.xml
- pom.xml
- src/main/java/com/hermesworld/ais/galapagos/certificates/impl/CaManagerImpl.java
- src/main/java/com/hermesworld/ais/galapagos/changes/config/GalapagosChangesConfig.java
- src/main/java/com/hermesworld/ais/galapagos/graphql/GraphqlController.java
- src/main/java/com/hermesworld/ais/galapagos/naming/config/NamingConfig.java
- src/main/java/com/hermesworld/ais/galapagos/notifications/config/GalapagosMailConfig.java
- src/main/java/com/hermesworld/ais/galapagos/notifications/impl/NotificationEventListener.java
- src/main/resources/application.properties
- src/main/resources/graphql/schema.graphqls
- src/test/java/com/hermesworld/ais/galapagos/applications/impl/ApplicationsServiceImplTest.java
- src/test/java/com/hermesworld/ais/galapagos/applications/impl/ApplicationsServiceRequestStatesImplTest.java
- src/test/java/com/hermesworld/ais/galapagos/graphql/GraphqlControllerTest.java
- src/test/java/com/hermesworld/ais/galapagos/topics/impl/ValidatingTopicServiceImplTest.java
Introduces querying for specific TopicMetaData in GraphQl.
> Add GraphQL interface for metadata

- pom.xml
This fixes some security issues, e.g. [CVE-2024-38819](https://www.cve.org/CVERecord?id=CVE-2024-38819)
> Update Spring Webflux and Webmvc to 6.1.14

- .mvn/wrapper/maven-wrapper.properties
> Update maven issue384
